  version: '3.7'

  services:
    flask_app:
      build: '/Users/mariomcgee/Documents/Sen_term3/flask-dockerized'
      #image: 'nlp_flask-dockerized:latest'
      env_file:
        - './.env'
    web:
      build: .
      ports:
        - "5000:5000"
      command: flask run --host=0.0.0.0
  

        
       
  
